#!/usr/bin/env bash
# Common shell configuration sourced by both bashrc and zshrc

# Change this to 'server' to get the prompt to look different
# do this in .this_machine if you're clever
[ -z "$bash_display_style" ] && \
  bash_display_style=normal

# Source in additional resource files if they exist
[ -e $HOME/.dev_env ] && . $HOME/.dev_env
[ -e $HOME/.mac_fixes ] && . $HOME/.mac_fixes
[ -e $HOME/.app_secrets ] && source $HOME/.app_secrets
[ -e $HOME/.work_specific ] && source $HOME/.work_specific
source $HOME/.my_aliases
[ -e $HOME/.this_machine ] && source $HOME/.this_machine

export PATH="/$HOME/bin:$PATH"



## Setup git
# export GIT_AUTHOR_NAME=$MY_FULL_NAME
# export GIT_AUTHOR_EMAIL=$MY_EMAIL
# export GIT_COMMITTER_NAME=$MY_FULL_NAME
# export GIT_COMMITTER_EMAIL=$MY_FULL_NAME

## setup git to use vim and not NANO
export VISUAL=vim
export EDITOR=vim


# If not running interactively, don't do anything
[ -z "$PS1" ] && return


######################
# History Settings   #
######################

HISTSIZE=20000


# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt (bs)
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  # We have color support; assume it's compliant with Ecma-48
  # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
  # a case would tend to support setf rather than setaf.)
  color_prompt=yes
    else
  color_prompt=
    fi
fi


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

